---    
- name: Add key for NVIDIA CUDA repos
  apt_key:
    url: http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
    state: present

- name: Add repo for NVIDIA CUDA drivers
  apt_repository:
    repo: "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 /"

- name: Install CUDA 11.4
  apt:
    name:
      - cuda=11.4.0-1
      - cuda-11-4=11.4.0-1
      - cuda-runtime-11-4=11.4.0-1
      - cuda-drivers=470.57.02-1
      - cuda-drivers-470=470.57.02-1
      - nvidia-driver-470=470.57.02-0ubuntu1
      - libnvidia-gl-470=470.57.02-0ubuntu1
      - nvidia-dkms-470=470.57.02-0ubuntu1
      - nvidia-kernel-source-470=470.57.02-0ubuntu1
      - nvidia-kernel-common-470=470.57.02-0ubuntu1
      - libnvidia-common-470=470.57.02-0ubuntu1
      - libnvidia-compute-470=470.57.02-0ubuntu1
      - libnvidia-extra-470=470.57.02-0ubuntu1
      - nvidia-compute-utils-470=470.57.02-0ubuntu1
      - libnvidia-decode-470=470.57.02-0ubuntu1
      - libnvidia-encode-470=470.57.02-0ubuntu1
      - xserver-xorg-video-nvidia-470=470.57.02-0ubuntu1
      - nvidia-modprobe=470.57.02-0ubuntu1
      - nvidia-utils-470=470.57.02-0ubuntu1
      - libnvidia-cfg1-470=470.57.02-0ubuntu1
      - libnvidia-ifr1-470=470.57.02-0ubuntu1
      - libnvidia-fbc1-470=470.57.02-0ubuntu1
    state: present
    install_recommends: no
    update_cache: yes

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Hold CUDA Packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - cuda
    - cuda-11-4
    - cuda-runtime-11-4
    - cuda-drivers
    - cuda-drivers-470
    - nvidia-driver-470
    - libnvidia-gl-470
    - nvidia-dkms-470
    - nvidia-kernel-source-470
    - nvidia-kernel-common-470
    - libnvidia-common-470
    - libnvidia-compute-470
    - libnvidia-extra-470
    - nvidia-compute-utils-470
    - libnvidia-decode-470
    - libnvidia-encode-470
    - xserver-xorg-video-nvidia-470
    - nvidia-modprobe
    - nvidia-utils-470
    - libnvidia-cfg1-470
    - libnvidia-ifr1-470
    - libnvidia-fbc1-470
  
- name: Install nvidia docker apt key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey

- name: Add nvidia-docker sources list
  get_url:
    url: https://nvidia.github.io/nvidia-docker/ubuntu18.04/nvidia-docker.list
    dest: /etc/apt/sources.list.d/nvidia-docker.list

- name: Install nvidia-docker2
  apt:
    name: nvidia-docker2
    state: latest
    update_cache: yes

- name: Create jenkins user
  user:
    name: jenkins
    groups:
      - docker
      - wheel
    uid: 10000
    append: yes

- name: Add authorized keys
  authorized_key:
    user: jenkins
    key: '{{ item }}'
  with_file:
    - ../../common/files/jenkins-prod.id_rsa.pub
    - ../../common/files/jenkins-ec2.id_rsa.pub

- name: Initialize git-lfs
  command: git lfs install
  become: yes
  become_user: jenkins

- name: Reboot
  reboot: {}
